In [4]:
import os
import pandas as pd
from datetime import datetime as dt

from sabotage.arguments import  build
from sabotage.train import run

import tensorflow as tf


# Set python level verbosity
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.DEBUG)

# Set C++ Graph Execution level verbosity
os.environ['TF_CPP_MIN_LOG_LEVEL'] = str(tf.compat.v1.logging.DEBUG)

base_path = "/mnt/disks/data/fma/trains"
id = "hierarchical_single"


In [5]:


train_path = os.path.join(base_path,id)
tfrecords_path =os.path.join(train_path,'tfrecords')
metadata_path = os.path.join(train_path,"metadata.json")
labels_path = os.path.join(train_path,"labels.json")


args = pd.Series({
    "batch_size":64,
    "epochs":10,
    "dropout":0.5,
    'patience':1,
    'max_queue_size':64,
    "labels_path": labels_path,
    "metadata_path": metadata_path,
    "trainset_pattern": os.path.join(tfrecords_path,'train'),
    "testset_pattern": os.path.join(tfrecords_path,'test'),
    "valset_pattern": os.path.join(tfrecords_path,'val')
})



In [3]:

time_start = dt.utcnow()
print("[{}] Experiment started at {}".format(id, time_start.strftime("%H:%M:%S")))
print(".......................................")
print(args)
run(args)
time_end = dt.utcnow()
time_elapsed = time_end - time_start
print(".......................................")
print("[{}] Experiment finished at {} / elapsed time {}s".format(id, time_end.strftime("%H:%M:%S"), time_elapsed.total_seconds()))

[hierarchical_single] Experiment started at 20:23:13
.......................................
batch_size                                                         64
epochs                                                             10
dropout                                                           0.5
patience                                                            1
max_queue_size                                                     64
labels_path         /mnt/disks/data/fma/trains/hierarchical_single...
metadata_path       /mnt/disks/data/fma/trains/hierarchical_single...
trainset_pattern    /mnt/disks/data/fma/trains/hierarchical_single...
testset_pattern     /mnt/disks/data/fma/trains/hierarchical_single...
valset_pattern      /mnt/disks/data/fma/trains/hierarchical_single...
dtype: object
batch_size                                                         64
epochs                                                             10
dropout                                              

/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/optimizers/legacy/adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)
2023-05-15 17:23:14.047527: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [1]
	 [[{{node Placeholder/_0}}]]


({'emb': <tf.Tensor: shape=(1280,), dtype=float32, numpy=
array([ 0.02865472,  0.01599024,  0.01095877, ...,  0.00357523,
        0.18488634, -0.03631104], dtype=float32)>}, {'first_level_output': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'second_level_output': <tf.Tensor: shape=(), dtype=int64, numpy=18>, 'third_level_output': <tf.Tensor: shape=(), dtype=int64, numpy=21>, 'fourth_level_output': <tf.Tensor: shape=(), dtype=int64, numpy=59>, 'fifth_level_output': <tf.Tensor: shape=(), dtype=int64, numpy=12>})
({'emb': <tf.Tensor: shape=(1280,), dtype=float32, numpy=
array([-0.04577968, -0.02855954,  0.00807128, ...,  0.00638578,
        0.19534464, -0.09547868], dtype=float32)>}, {'first_level_output': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'second_level_output': <tf.Tensor: shape=(), dtype=int64, numpy=9>, 'third_level_output': <tf.Tensor: shape=(), dtype=int64, numpy=22>, 'fourth_level_output': <tf.Tensor: shape=(), dtype=int64, numpy=57>, 'fifth_level_output': <tf.Tensor: sh

2023-05-15 17:23:14.245962: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [2]
	 [[{{node Placeholder/_0}}]]


ValueError: in user code:

    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/engine/training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/engine/training.py", line 1268, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/engine/training.py", line 1249, in run_step  **
        outputs = model.train_step(data)
    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/engine/training.py", line 1051, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/engine/training.py", line 1109, in compute_loss
        return self.compiled_loss(
    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/engine/compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/losses.py", line 142, in __call__
        losses = call_fn(y_true, y_pred)
    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/losses.py", line 268, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/losses.py", line 1984, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "/home/bruno/anaconda3/envs/fma/lib/python3.11/site-packages/keras/backend.py", line 5559, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes () and (None, 2) are incompatible
